{if !empty($newsbatch)}
    {foreach $new in $newsbatch}
        <div class="news">
            <a href="/aktuality/r/{echo $new->urlKey}"><span class="newsTitle">{echo $new->title}</span></a><br/>
            <span class="newsCreated">{echo $new->created}</span><br/>
            <p class="newsBody">{echo html_entity_decode($new->shortBody)}</p>
        </div>
    {/foreach}
    {if $newspagecount > 1}
    <div class="pageCounter">
        <ul>
        {for $i=1 $i<=$newspagecount $i++}
           <a title="{echo $i}"  href="/aktuality/p/{echo $i}"> <li>{echo $i}</li></a>
        {/for}
        </ul>
    </div>
    {/if}
{/if}{else}
    <div class='whiteBg'>
        Nejsou žádné aktuality
    </div>
{/else}


