<!doctype html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Content-Language" content="cs" />
        <title>Application</title>
        <!---CSS Files-->
        <link rel="stylesheet" href="/public/css/custom/errorStyle.min.css">
    </head>
    <body>
        <div class="content container_12">
            <h1 id="error-heading">PHP Version</h1>
            <p id="error-desc">PHP 5.4 and newer is required</p>
        </div>
        
        <div class="footer container_12">
            <p class="grid_12">THCFrame Error Page</p>
        </div>

    </body>
</html>