<ul class="maintabmenu multipletabmenu">
    <li class="current"><a href="#">Novinky</a></li>
    <li><a href="/admin/news/add/">Přidat novinku</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="image"><span>Novinky</span></h2>
    </div><!--contenttitle-->
    
    <form method="post" class="massActionForm" action="/admin/news/massAction/">
        <input type="hidden" name="tk" id="tk" value="{echo $token}" />
        <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
            <colgroup>
                <col class="con0" /> <col class="con1" />
                <col class="con0" /> <col class="con1" />
                <col class="con0" /> <col class="con1" />
            </colgroup>
            <thead>
                <tr>
                    <td class="head0 width50"><input type="checkbox" class="checkall" /></td>
                    <td class="head1">Název</td>
                    <td class="head0">Autor</td>
                    <td class="head1">Zobrazovat do</td>
                    <td class="head0">Vytvořeno</td>
                    <td class="head1">&nbsp;</td>
                </tr>
            </thead>
            <tbody>
                {if !empty($news)}
                    {foreach $_news in $news}
                        {if ($_news->active)}
                            <tr class="rowActive">
                        {/if} 
                        {else}
                            <tr>
                        {/else}
                            <td class="center">
                                <input type="checkbox" name="newsids[]" value="{echo $_news->getId()}" />
                            </td>
                            <td>{echo $_news->getTitle()}</td>
                            <td>{echo $_news->getAuthor()}</td>
                            <td>{echo $_news->getExpirationDate()}</td>
                            <td>{echo $_news->getCreated()}</td>
                            <td>
                                <a href="/admin/news/edit/{echo $_news->id}" class="btn btn3 btn_pencil" title="Upravit"></a>
                                {if $isAdmin}<a href="/admin/news/delete/{echo $_news->id}" class="btn btn3 btn_trash deleteRow" title="Smazat"></a>{/if}
                            </td>
                        </tr>
                    {/foreach}
                {/if}
            </tbody>
        </table>
        {if $isAdmin}
        <div class="tableoptions">
            Selected:
            <select class="radius3" name="action">
                <option value="activate">Aktivovat</option>
                <option value="deactivate">Deaktivovat</option>
                <option value="delete">Smazat</option>
            </select> &nbsp;
            <input class="radius3" type="submit" name="performNewsAction" value="Provést"/>
        </div><!--tableoptions-->
        {/if}
    </form>
</div>
<br class="clear-all"/><br />