<div class="widgetbox">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Photo properties</span></h2>
    </div><!--contenttitle-->

    <form class="stdform stdform2" method="post" action="#" >
        <p>
            <label>Float</label>
            <span class="field">
                <select id="photo-float">
                    <option value="none">None</option>
                    <option value="left">Left</option>
                    <option value="right">Right</option>
                </select>
            </span>
        </p>
    </form>
</div>