<ul>
    <li class="current"><a href="/admin/" class="dashboard"><span>Dashboard</span></a></li>
    <li><a href="/admin/news/" class="tables"><span>Novinky</span></a></li>
    <li><a href="/admin/dog/" class="grid"><span>Psi</span></a></li>
    <li><a href="/admin/gallery/" class="media"><span>Galerie</span></a></li>
    <li><a href="/admin/content/" class="editor"><span>Obsah webu</span></a></li>
    <li><a href="/admin/exam/" class="tables"><span>Zkoušky</span></a></li>
    <li><a href="/admin/link/" class="tables"><span>Odkazy</span></a></li>
    {if $isAdmin || $isSuperAdmin}
    <li><a href="/admin/user/" class="users"><span>Uživatelé</span></a></li>
    <li><a href="/admin/system/" class="error"><span>Nastavení</span></a></li>
    {/if}
</ul>