<div class="whiteBg">
    <div class="center">
        <span class="galDetailTitle">{$gallery->title}</span>
    </div>
    <p class="galDetailBody">{$gallery->description}</p>
    {script $photos = $gallery->getPhotos()}
    {if !empty($photos)}
        {foreach $bla in $photos}
            <div class="galDetailImgs">
                <a data-lightbox="imageGr" data-title="echo {$bla->getTitle()}" href="{$bla->getImgMain()}" alt="{echo $bla->getTitle()}"> <img src="{echo $bla->getImgThumb()}"/></a>
            </div>
        {/foreach}
    {/if}
</div>
