<div class="widgetbox">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Zarovnaní</span></h2>
    </div><!--contenttitle-->

    <form class="stdform stdform2" method="post" action="#" >
        <p>
            <label>Zarovnání</label>
            <span class="field">
                <select id="photo-float">
                    <option value="none">Žádné</option>
                    <option value="left">Vlevo</option>
                    <option value="right">Vpravo</option>
                </select>
            </span>
        </p>
    </form>
</div>