<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/user/">Uživatelé</a></li>
    <li class="current"><a href="#">Nový uživatel</a></li>
</ul>

<div class="content">

    <form class="stdform stdform2 cropit-form" method="post" action="#" enctype="multipart/form-data">
        <input type="hidden" name="tk" id="tk" value="{echo $token}" />
        <input type="hidden" name="submstoken" id="submstoken" value="{echo $submstoken}" />
        <input type="hidden" name="croppedimage" class="cropit-hidden-resized-image" value="" />

        <div class="contenttitle radiusbottom0">
            <h2 class="form"><span>Osobní údaje</span></h2>
        </div>
        <p>
            <label>Jméno*</label>
            <span class="field">
                <input required type="text" name="firstname" class="longinput" value="{echo isset($user)? $user->firstname: ""}" />
            </span>
            {if isset($errors["firstname"])}
            <label class="error">
                {echo join("<br/>", $errors["firstname"])}
            </label>
            {/if}
        </p>
        <p>
            <label>Příjmení*</label>
            <span class="field">
                <input required type="text" name="lastname" class="longinput" value="{echo isset($user)? $user->lastname: ""}" />
            </span>
            {if isset($errors["lastname"])}
            <label class="error">
                {echo join("<br/>", $errors["lastname"])}
            </label>
            {/if}
        </p>
        <div class="par">
            <label>Profilová fotka*<small>*.jpg, *.jpeg, *.png, *.gif</small></label>
            <div id="image-cropper" class="field">
                <input type="file" class="cropit-image-input" accept="image/*"/>
                <div class="cropit-image-preview-container">
                    <div class="cropit-image-background-container">
                        <img class="cropit-image-background" />
                    </div>
                    <div class="cropit-image-preview"></div>
                </div>

                <input type="range" class="cropit-image-zoom-input" />
                {if isset($errors["croppedimage"])}
                <label class="error">
                    {echo join("<br/>", $errors["croppedimage"])}
                </label>
                {/if}
            </div>
        </div>
        <br/>
        <div class="contenttitle radiusbottom0">
            <h2 class="form"><span>Přihlašovací údaje</span></h2>
        </div>
        <p>
            <label>Email*</label>
            <span class="field">
                <input required type="email" name="email" class="longinput" value="{echo isset($user)? $user->email: ""}" />
            </span>
            {if isset($errors["email"])}
            <label class="error">
                {echo join("<br/>", $errors["email"])}
            </label>
            {/if}
        </p>
        <p>
            <label>Heslo*</label>
            <span class="field">
                <input required type="password" name="password" class="longinput" value=""/>
            </span>
            {if isset($errors["password"])}
            <label class="error">
                {echo join("<br/>", $errors["password"])}
            </label>
            {/if}
        </p>
        <p>
            <label>Potvrdit heslo*</label>
            <span class="field">
                <input required type="password" name="password2" class="longinput" value=""/>
            </span>
            {if isset($errors["password2"])}
            <label class="error">
                {echo join("<br/>", $errors["password2"])}
            </label>
            {/if}
        </p>
        {if $isSuperAdmin}
        <p>
            <label>Role</label>
            <span class="field">
                <select name="role" class="longinput">
                    <option value="role_member">Member</option>
                    <option value="role_admin">Admin</option>
                    <option value="role_superadmin">Super Admin</option>
                </select>
            </span>
            {if isset($errors["role"])}
            <label class="error">
                {echo join("<br/>", $errors["role"])}
            </label>
            {/if}
        </p>
        {/if}

        <p class="stdformbutton">
            <input type="submit" name="submitAddUser" value="Uložit" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>
</div>