<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/user/">Uživatelé</a></li>
    <li><a href="/admin/user/add/">Nový uživatel</a></li>
    <li class="current"><a href="#">Editovat uživatele</a></li>
</ul>

<div class="content">
    <form class="stdform stdform2" method="post" action="#" enctype="multipart/form-data">
        <input type="hidden" name="tk" id="tk" value="{echo $token}" />

        <div class="contenttitle radiusbottom0">
            <h2 class="form"><span>Osobní údaje</span></h2>
        </div>
        <p>
            <label>Jméno*</label>
            <span class="field">
                <input required type="text" name="firstname" class="longinput" value="{echo isset($user)? $user->firstname: ""}" />
            </span>
            {if isset($errors["firstname"])}
            <label class="error">
                {echo join("<br/>", $errors["firstname"])}
            </label>
            {/if}
        </p>
        <p>
            <label>Příjmení*</label>
            <span class="field">
                <input required type="text" name="lastname" class="longinput" value="{echo isset($user)? $user->lastname: ""}" />
            </span>
            {if isset($errors["lastname"])}
            <label class="error">
                {echo join("<br/>", $errors["lastname"])}
            </label>
            {/if}
        </p>

        <br/>
        <div class="contenttitle radiusbottom0">
            <h2 class="form"><span>Přihlašovací údaje</span></h2>
        </div>
        <p>
            <label>Email*</label>
            <span class="field">
                <input required type="email" name="email" class="longinput" value="{echo isset($user)? $user->email: ""}" />
            </span>
            {if isset($errors["email"])}
            <label class="error">
                {echo join("<br/>", $errors["email"])}
            </label>
            {/if}
        </p>
        <p>
            <label>Heslo*</label>
            <span class="field">
                <input required type="password" name="password" class="longinput" value=""/>
            </span>
            {if isset($errors["password"])}
            <label class="error">
                {echo join("<br/>", $errors["password"])}
            </label>
            {/if}
        </p>
        <p>
            <label>Potvrdit heslo*</label>
            <span class="field">
                <input required type="password" name="password2" class="longinput" value=""/>
            </span>
            {if isset($errors["password2"])}
            <label class="error">
                {echo join("<br/>", $errors["password2"])}
            </label>
            {/if}
        </p>
        <p>
            <label>Aktivní</label>
            <span class="field">
                <select name="active" class="longinput">
                    {if $user->active == 1}
                    <option value="0">Neaktivní</option>
                    <option value="1" selected>Aktivní</option>
                    {/if}
                    {else}
                    <option value="0" selected>Neaktivní</option>
                    <option value="1">Aktivní</option>
                    {/else}
                </select>
            </span>
        </p>

        {if $isSuperAdmin}
        <p>
            <label>Role</label>
            <span class="field">
                <select name="role" class="longinput">
                    {if $user->role == "role_superadmin"}
                    <option value="role_member">Member</option>
                    <option value="role_admin">Admin</option>
                    <option value="role_superadmin" selected>Super Admin</option>
                    {/if}
                    {elseif $user->role == "role_admin"}
                    <option value="role_member">Member</option>
                    <option value="role_admin" selected>Admin</option>
                    <option value="role_superadmin">Super Admin</option>
                    {/elseif}
                    {else}
                    <option value="role_member" selected>Member</option>
                    <option value="role_admin">Admin</option>
                    <option value="role_superadmin">Super Admin</option>
                    {/else}
                </select>
            </span>
            {if isset($errors["role"])}
            <label class="error">
                {echo join("<br/>", $errors["role"])}
            </label>
            {/if}
        </p>
        {/if}

        <br/>
        <div class="contenttitle radiusbottom0">
            <h2 class="table"><span>Psi</span></h2>
        </div>
        <table cellpadding="0" cellspacing="0" border="0" class="stdtable" >
            <colgroup>
                <col class="con0" /><col class="con1" />
                <col class="con0" /><col class="con1" />
                <col class="con0" /><col class="con1" />
            </colgroup>
            <thead>
                <tr>
                    <th class="head0">Jméno</th><th class="head1">Foto</th>
                    <th class="head0">Rasa</th><th class="head1">Narozen</th>
                    <th class="head0">Aktivní</th><th class="head1">&nbsp;</th>
                </tr>
            </thead>
            <tbody>

                {if (!empty($dogs))}
                {foreach $dog in $dogs}
                <tr>
                    <td>{echo $dog->getDogName()}</td>
                    <td><img src="{echo $dog->getImgThumb()}" alt="" /></td>
                    <td>{echo $dog->getRace()}</td>
                    <td>{echo $dog->getDob()}</td>
                    {if $dog->active}
                    <td>Active</td>
                    {/if}
                    {else}
                    <td>Inactive</td>
                    {/else}

                    <td>
                        <a href="/admin/dog/edit/{echo $dog->id}" class="btn btn3 btn_pencil"></a> 
                        {if $isAdmin}<a href="/admin/dog/delete/{echo $dog->id}" class="btn btn3 btn_trash deleteRow"></a>{/if}
                    </td>
                </tr>
                {/foreach}
                {/if}
            </tbody>
        </table>

        <p class="stdformbutton">
            <input type="submit" name="submitEditUser" value="Uložit změny" />
        </p>
    </form>
</div>