<ul class="maintabmenu multipletabmenu">
    <li class="current"><a href="#">Uživatelé</a></li>
    <li><a href="/admin/user/add/">Nový uživatel</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Uživatelé</span></h2>
    </div><!--contenttitle-->

    <input type="hidden" name="tk" id="tk" value="{echo $token}" />
    <table cellpadding="0" cellspacing="0" border="0" class="stdtable" >
        <colgroup>
            <col class="con0" /><col class="con1" />
            <col class="con0" /><col class="con1" />
            <col class="con0" /><col class="con1" />
        </colgroup>
        <thead>
            <tr>
                <th class="head0">Jméno</th><th class="head1">Příjmení</th>
                <th class="head0">Email</th><th class="head1">Vytvořeno</th>
                <th class="head0">Status</th><th class="head1">&nbsp;</th>
            </tr>
        </thead>
        <tbody>

            {if (!empty($users))}
                {foreach $user in $users}
                    <tr>
                        <td>{echo $user->getFirstname()}</td>
                        <td>{echo $user->getLastname()}</td>
                        <td>{echo $user->getEmail()}</td>
                        <td>{echo $user->getCreated()}</td>
                        <td>
                            {if ($user->active)}<span class="labelProduct labelProductGreen">Aktivní</span>{/if}
                            {if $user->getRole() == "role_member"}<span class="labelProduct labelProductBlue">Člen</span>{/if}
                            {if $user->getRole() == "role_admin"}<span class="labelProduct labelProductBlue">Admin</span>{/if}
                        </td>

                        <td>
                            <a href="/admin/user/edit/{echo $user->id}" class="btn btn3 btn_pencil" title="Upravit"></a> 
                            {if $isSuperAdmin}<a href="/admin/user/delete/{echo $user->id}" class="btn btn3 btn_trash deleteRow" title="Smazat"></a>{/if}
                        </td>
                    </tr>
                {/foreach}
            {/if}
        </tbody>
    </table>
</div>