<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/dog/">Psi</a></li>
    <li class="current"><a href="#">Nový pes</a></li>
</ul>

<div class="content">

    <form class="stdform stdform2 uploadCollectionPhotoForm cropit-form" method="post" action="#" enctype="multipart/form-data">
        <input type="hidden" name="tk" id="tk" value="{echo $token}" />
        <input type="hidden" name="submstoken" id="submstoken" value="{echo $submstoken}" />
        <input type="hidden" name="croppedimage" class="cropit-hidden-resized-image" value="" />

        <div class="contenttitle radiusbottom0">
            <h2 class="form"><span>Pes</span></h2>
        </div>
        <p>
            <label>Jméno psa*</label>
            <span class="field">
                <input required type="text" name="dogname" class="longinput" value="{echo isset($dog)? $dog->dogName: ""}" />
                {if isset($errors["dogName"])}
                <label class="error">
                    {echo join("<br/>", $errors["dogName"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Majitel*</label>
            <span class="field">
                <select name="user" class="longinput">
                    {if !empty($users)}
                    {foreach $user in $users}
                    <option value="{echo $user->id}">{echo $user->firstname." ".$user->lastname}</option>
                    {/foreach}
                    {/if}
                </select>
                {if isset($errors["user"])}
                <label class="error">
                    {echo join("<br/>", $errors["user"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Aktuální pes</label>
            <span class="field">
                <select name="isactive" class="longinput">
                    <option value="0">Ne</option>
                    <option value="1">Ano</option>
                </select>
            </span>
        </p>
        <div class="par">
            <label>Hlavní fotka*<small>*.jpg, *.jpeg, *.png, *.gif</small></label>
            <div id="image-cropper" class="field">
                <input type="file" class="cropit-image-input" accept="image/*"/>
                <div class="cropit-image-preview-container">
                    <div class="cropit-image-background-container">
                        <img class="cropit-image-background" />
                    </div>
                    <div class="cropit-image-preview"></div>
                </div>

                <input type="range" class="cropit-image-zoom-input" />
                {if isset($errors["croppedimage"])}
                <label class="error">
                    {echo join("<br/>", $errors["croppedimage"])}
                </label>
                {/if}
            </div>
        </div>
        <p>
            <label>Rasa*</label>
            <span class="field">
                <input required type="text" name="dograce" class="longinput" value="{echo isset($dog)? $dog->race: ""}" />
                {if isset($errors["race"])}
                <label class="error">
                    {echo join("<br/>", $errors["race"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Datum narození</label>
            <span class="field">
                <input type="text" name="dogdob" class="longinput datepicker" value="{echo isset($dog)? $dog->dob: ""}" />
                {if isset($errors["dob"])}
                <label class="error">
                    {echo join("<br/>", $errors["dob"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Další informace</label>
            <span class="field">
                <textarea name="doginfo" class="longinput" rows="5">{echo isset($dog)? $dog->information : ""}</textarea>
                {if isset($errors["information"])}
                <label class="error">
                    {echo join("<br/>", $errors["information"])}
                </label>
                {/if}
            </span>
        </p>

        <br/>
        <div class="contenttitle radiusbottom0">
            <h2 class="form"><span>Další fotografie</span></h2>
        </div>
        <p>
            <label>Nahrát více fotografií</label>
            <span class="field">
                <select name="uploadmorephotos" class="longinput">
                    <option value="0">Ne</option>
                    <option value="1">Ano</option>
                </select>
            </span>
        </p>
        <p>
            <label>Foto<small>*.jpg, *.jpeg, *.png, *.gif</small></label>
            <span class="field">
                <a href="#" class="btn btn_folder multi_upload"><span>+</span></a>
                <a href="#" class="btn btn_folder multi_upload_dec"><span>-</span></a>
            </span>
            <span class="field file_inputs">
                <input type="file" name="secondfile[]"/>
                {if isset($errors["secondfile"])}
                <label class="error">
                    {echo join("<br/>", $errors["secondfile"])}
                </label>
                {/if}
            </span>
        </p>

        <br/>
        <div class="contenttitle radiusbottom0">
            <h2 class="form"><span>Zkoušky</span></h2>
        </div>
        <div class="par">
            <label>Zkoušky</label>
            <div class="field">
                {if !empty($exams)}
                    <ul class="category-tree">
                        {foreach $exam in $exams}
                        <li>
                            <input type="checkbox" name="chexam[]" value="{echo $exam->id}" /><span>{echo $exam->title}</span>
                        </li>
                        {/foreach}
                    </ul>
                {/if}
                {if isset($errors["exam"])}
                <label class="error">{echo join("<br/>", $errors["exam"])}</label>
                {/if}
            </div>
        </div>

        <p class="stdformbutton">
            <input type="submit" name="submitAddDog" value="Uložit" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>
</div>