<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/dog/">Psi</a></li>
    <li><a href="/admin/dog/add/">Nový pes</a></li>
    <li class="current"><a href="#">Editovat psa</a></li>
</ul>

<div class="content">
    <form class="stdform stdform2 uploadForm cropit-form" method="post" action="#" enctype="multipart/form-data">
        <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
        <input type="hidden" name="croppedimage" class="cropit-hidden-resized-image" value="" />

        <div class="contenttitle radiusbottom0">
            <h2 class="form"><span>Pes</span></h2>
        </div>
        <p>
            <label>Jméno psa*</label>
            <span class="field">
                <input required type="text" name="dogname" class="longinput" value="{echo $dog->dogName}" />
                {if isset($errors["dogName"])}
                <label class="error">
                    {echo join("<br/>", $errors["dogName"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Majitel*</label>
            <span class="field">
                <select name="user" class="longinput">
                    {if !empty($users)}
                    {foreach $user in $users}
                    {script $sel=""}
                    {if $dog->userId == $user->id}
                    {script $sel="selected"}
                    {/if}
                    <option value="{echo $user->id}" {echo $sel}>{echo $user->firstname." ".$user->lastname}</option>
                    {/foreach}
                    {/if}
                </select>
                {if isset($errors["user"])}
                <label class="error">
                    {echo join("<br/>", $errors["user"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Aktuální pes</label>
            <span class="field">
                <select name="isactive" class="longinput">
                    {if $dog->isActive == 1}
                    <option value="0">Ne</option>
                    <option value="1" selected>Ano</option>
                    {/if}{else}
                    <option value="0" selected>Ne</option>
                    <option value="1">Ano</option>
                    {/else}
                </select>
            </span>
        </p>
        <div class="par">
            <label>Hlavní fotka*<small>*.jpg, *.jpeg, *.png, *.gif</small></label>
            {if $dog->imgMain != ""}
            <span class="field" id="currentLogo">
                <img src="{echo $dog->imgThumb}" alt="" height="100" />
                <a href="/admin/dog/deletemainphoto/{echo $dog->id}" class="btn btn3 btn_trash deleteImg" title="Smazat"></a>
            </span>

            <div id="image-cropper" class="uploadNewImage nodisplay field">
                <input type="file" class="cropit-image-input" accept="image/*"/>
                <div class="cropit-image-preview-container">
                    <div class="cropit-image-background-container">
                        <img class="cropit-image-background" />
                    </div>
                    <div class="cropit-image-preview"></div>
                </div>

                <input type="range" class="cropit-image-zoom-input" />
                {if isset($errors["croppedimage"])}
                <label class="error">
                    {echo join("<br/>", $errors["croppedimage"])}
                </label>
                {/if}
            </div>
            {/if}{else}
            <div id="image-cropper" class="uploadNewImage field">
                <input type="file" class="cropit-image-input" accept="image/*"/>
                <div class="cropit-image-preview-container">
                    <div class="cropit-image-background-container">
                        <img class="cropit-image-background" />
                    </div>
                    <div class="cropit-image-preview"></div>
                </div>

                <input type="range" class="cropit-image-zoom-input" />
                {if isset($errors["croppedimage"])}
                <label class="error">
                    {echo join("<br/>", $errors["croppedimage"])}
                </label>
                {/if}
            </div>
            {/else}
        </div>
        <p>
            <label>Rasa*</label>
            <span class="field">
                <input required type="text" name="dograce" class="longinput" value="{echo $dog->race}" />
                {if isset($errors["race"])}
                <label class="error">
                    {echo join("<br/>", $errors["race"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Datum narození*</label>
            <span class="field">
                <input required type="text" name="dogdob" class="longinput datepicker" value="{echo $dog->dob}" />
                {if isset($errors["dob"])}
                <label class="error">
                    {echo join("<br/>", $errors["dob"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Další informace</label>
            <span class="field">
                <textarea name="doginfo" class="longinput" rows="5">{echo $dog->information}</textarea>
                {if isset($errors["information"])}
                <label class="error">
                    {echo join("<br/>", $errors["information"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Aktivní</label>
            <span class="field">
                <select name="active" class="longinput">
                    {if $dog->active == 1}
                    <option value="0">Neaktivní</option>
                    <option value="1" selected>Aktivní</option>
                    {/if}{else}
                    <option value="0" selected>Neaktivní</option>
                    <option value="1">Aktivní</option>
                    {/else}
                </select>
            </span>
        </p>

        <br/>
        <div class="contenttitle radiusbottom0">
            <h2 class="form"><span>Další fotografie</span></h2>
        </div>
        <p>
            <label>Nahrát více fotografií</label>
            <span class="field">
                <select name="uploadmorephotos" class="longinput">
                    <option value="0">Ne</option>
                    <option value="1">Ano</option>
                </select>
            </span>
        </p>
        <p>
            <label>Foto<small>*.jpg, *.jpeg, *.png, *.gif</small></label>
            <span class="field">
                <a href="#" class="btn btn_folder multi_upload"><span>+</span></a>
                <a href="#" class="btn btn_folder multi_upload_dec"><span>-</span></a>
            </span>
            <span class="field file_inputs">
                <input type="file" name="secondfile[]"/>
                {if isset($errors["secondfile"])}
                <label class="error">
                    {echo join("<br/>", $errors["secondfile"])}
                </label>
                {/if}
            </span> 
        </p>

        <br/>
        <div class="contenttitle radiusbottom0">
            <h2 class="form"><span>Další fotky</span></h2>
        </div>
        {script $photos = $dog->adPhoto}
        {if !empty($photos)}
            <div style="overflow:hidden;">
                <ul class="imagelist">
                    {foreach $photo in $photos}
                        {if $photo->active}
                        <li class="photoactive">
                            {/if}{else}
                        <li class="photoinactive">
                            {/else}
                            <a href="{echo $photo->imgMain}" data-lightbox="dog_photo">
                                <img src="{echo $photo->imgThumb}" alt="" height="120px" />
                            </a>
                            <span>
                                <a href="/admin/gallery/changephotostatus/{echo $photo->id}" class="activate" value="Změnit stav foto"></a>
                                <a href="/admin/gallery/deletephoto/{echo $photo->id}" class="delete" value="Smazat foto"></a>
                            </span>
                        </li>
                    {/foreach}
                </ul>
            </div>
        {/if}{else}
        <div class="notification msginfo"><a class="close"></a><p>Žádné foto</p></div>
        {/else}

        <br/>
        <div class="contenttitle radiusbottom0">
            <h2 class="form"><span>Zkoušky</span></h2>
        </div>
        <div class="par">
            <label>Zkoušky</label>
            <div class="field">
                {if !empty($exams)}
                    <ul class="category-tree">
                        {foreach $exam in $exams}
                        <li>
                            {script $ch = ""}
                            {if in_array($exam->getId(), $dogexamids)}
                            {script $ch = "checked=\"checked\""}
                            {/if}
                            <input type="checkbox" name="chexam[]" value="{echo $exam->id}" {echo $ch} /><span>{echo $exam->title}</span>
                        </li>
                        {/foreach}
                    </ul>
                {/if}
                {if isset($errors["exams"])}
                <label class="error">{echo join("<br/>", $errors["exams"])}</label>
                {/if}
            </div>
        </div>

        <p class="stdformbutton">
            <input type="submit" name="submitEditDog" value="Uložit změny" class="submit radius2" />
        </p>
    </form>
</div>