<ul class="maintabmenu multipletabmenu">
    <li class="current"><a href="#">Psi</a></li>
    <li><a href="/admin/dog/add/">Nový pes</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Psi</span></h2>
    </div><!--contenttitle-->

    <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
    <table cellpadding="0" cellspacing="0" border="0" class="stdtable" >
        <colgroup>
            <col class="con0" /><col class="con1" />
            <col class="con0" /><col class="con1" />
            <col class="con0" /><col class="con1" />
            <col class="con0" />
        </colgroup>
        <thead>
            <tr>
                <th class="head0">Jméno</th><th class="head1">Foto</th>
                <th class="head0">Rasa</th><th class="head1">Majitel</th>
                <th class="head0">Narozen</th><th class="head1">Status</th>
                <th class="head0">&nbsp;</th>
            </tr>
        </thead>
        <tbody>

            {if (!empty($dogs))}
                {foreach $dog in $dogs}
                    <tr>
                        <td>{echo $dog->getDogName()}</td>
                        <td><img src="{echo $dog->getImgThumb()}" alt="" height="150px" /></td>
                        <td>{echo $dog->getRace()}</td>
                        <td>{echo $dog->firstname." ".$dog->lastname}</td>
                        <td>{echo $dog->getDob()}</td>
                        <td>
                            {if $dog->active}<span class="labelProduct labelProductGreen">Aktivní</span>{/if}
                            {if $dog->isActive == 1}<span class="labelProduct labelProductBlue">Primární</span>{/if}
                        </td>
                        <td>
                            <a href="/admin/dog/edit/{echo $dog->id}" class="btn btn3 btn_pencil" title="Upravit"></a> 
                            <a href="/admin/dog/delete/{echo $dog->id}" class="btn btn3 btn_trash ajaxDelete" title="Smazat"></a>
                        </td>
                    </tr>
                {/foreach}
            {/if}
        </tbody>
    </table>
</div>