<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/system/">Hlavní</a></li>
    <li><a href="/admin/system/settings/">Nastavení</a></li>
    {if $isSuperAdmin}<li><a href="/admin/system/showadminlog/">Admin log</a></li>{/if}
    <li class="current"><a href="#">Smazané produkty</a></li>
</ul>
<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="form"><span>Smazané Produkty</span></h2>
    </div>

    <input type="hidden" name="tk" id="tk" value="{echo $token}" />
    <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
        <colgroup>
            <col class="con0" /> <col class="con1" />
            <col class="con0" /> <col class="con1" />
            <col class="con0" /> <col class="con1" />
            <col class="con0" />
        </colgroup>
        <thead>
            <tr>
                <th class="head0 width50">ID</th>
                <th class="head1">Obrázek</th>
                <th class="head0">Název</th>
                <th class="head1">Typ</th>
                <th class="head0">Kód produktu</th>
                <th class="head1">Současná cena</th>
                <th class="head0">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            {if !empty($deletedproducts)}
            {foreach $product in $deletedproducts}
            <tr>
                <td>{echo $product->getId()}</td>
                <td><img alt="" src="{echo $product->imgThumb}" height="80px" /></td>
                <td>{echo $product->getTitle()}</td>
                <td>{echo $product->getProductType()}</td>
                <td>{echo $product->getProductCode()}</td>
                <td>{echo $product->getCurrentPrice()}</td>
                <td>
                    <a href="/admin/product/undelete/{echo $product->id}" class="btn btn3 btn_refresh undeleteRow" title="Obnovit"></a>
                </td>
            </tr>
            {/foreach}
            {/if}
        </tbody>
    </table>
</div>