<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/gallery/">Galerie</a></li>
    <li class="current"><a href="#">Nová Galerie</a></li>
</ul><!--maintabmenu-->
<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Nová Galerie</span></h2>
    </div><!--contenttitle-->

    <form class="stdform stdform2" method="post" action="#" >
        <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
        <input type="hidden" name="submstoken" id="submstoken" value="{echo $submstoken}" />
        <p>
            <label>Název*</label>
            <span class="field">
                <input class="longinput" type="text" name="title" value="{echo isset($gallery)? $gallery->title: ""}" />
                {if isset($errors["title"])}
                <label class="error">{echo join("<br/>", $errors["title"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Veřejná/soukromá</label>
            <span class="field">
                <select class="longinput" name="active">
                    <option value="0">Soukromá</option>
                    <option value="1" selected>Veřejná</option>
                </select>
            </span>
        </p>
        <p>
            <label>Ke dni*</label>
            <span class="field">
                <input type="text" name="showdate" class="longinput datepicker" 
                       value="{echo isset($gallery)? $gallery->showDate: ""}"/>
                {if isset($errors["showDate"])}
                    <label class="error">{echo join("<br/>", $errors["showDate"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Popis*<small>Max. 30 000 znaků</small></label>
            <span class="field">
                <textarea class="longinput" name="description" id="ckeditor">{echo isset($gallery)? $gallery->description: ""}</textarea>
                {if isset($errors["description"])}
                <label class="error">{echo join("<br/>", $errors["description"])}</label>
                {/if}
            </span>
        </p>
        <p class="stdformbutton">
            <input name="submitAddGallery" type="submit" value="Uložit" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>
</div>
