<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/gallery/">Galerie</a></li>
    <li><a href="/admin/gallery/add/">Nová Galerie</a></li>
    <li><a href="/admin/gallery/detail/{echo $gallery->id}">Detail Galerie</a></li>
    <li class="current"><a href="#">Editovat Galerii</a></li>
    {if $isAdmin}<li><a href="/admin/gallery/delete/{echo $gallery->id}">Smazat Galerii</a></li>{/if}
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Nová Galerie</span></h2>
    </di><!--contenttitle-->
    
    <form class="stdform stdform2" method="post" action="#" >
        <input type="hidden" name="tk" id="tk" value="{echo $token}" />
        
        <p>
            <label>Název*</label>
            <span class="field">
                <input class="longinput" type="text" name="title" value="{echo $gallery->title}" />
                {if isset($errors["title"])}
                <label class="error">{echo join("<br/>", $errors["title"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Veřejná</label>
            <span class="field">
                <select class="longinput" name="active">
                    {if $gallery->isPublic == 0}
                    <option value="0" selected>Soukromá</option>
                    <option value="1">Veřejná</option>
                    {/if}{else}
                    <option value="0">Soukromá</option>
                    <option value="1" selected>Veřejná</option>
                    {/else}
                </select>
            </span>
        </p>
        <p>
            <label>Popis*<small>Max. 30 000 znaků</small></label>
            <span class="field">
                <textarea class="longinput" name="description" id="ckeditor">{echo $gallery->description}</textarea>
                {if isset($errors["description"])}
                <label class="error">{echo join("<br/>", $errors["description"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Aktivní</label>
            <span class="field">
                <select class="longinput" name="active">
                    {if $gallery->active == 0}
                    <option value="0" selected>Neaktivní</option>
                    <option value="1">Aktivní</option>
                    {/if}{else}
                    <option value="0">Neaktivní</option>
                    <option value="1" selected>Aktivní</option>
                    {/else}
                </select>
            </span>
        </p>
        <p class="stdformbutton">
            <input name="submitEditGallery" type="submit" value="Uložit" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>
</div>