<script type="text/javascript" src="/public/js/custom/dashboard.js"></script>
<ul class="maintabmenu">
    <li class="current"><a href="/admin/">Dashboard</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <ul class="widgetlist">
        <li><a href="/admin/news/add/" class="events">Nová novinka</a></li>
        <li><a href="/admin/dog/add/" class="message">Nový pes</a></li>
        <li><a href="/admin/user/add/" class="message">Nový člen</a></li>
        <li><a href="/admin/gallery/add/" class="upload">Nová galerie</a></li>
    </ul>

    <br clear="all" /><br />

    <div class="one_half">
        <div class="widgetbox">
            <div class="title"><h2 class="calendar"><span>Poslední novinky</span></h2></div>
            <div class="widgetcontent announcement">
                {if !empty($latestnews)}
                    {foreach $news in $latestnews}
                        <p>
                            <span class="radius2">Title: {echo $news->getTitle()}</span>
                            <span class="radius2">Created: {echo $news->getCreated()}</span>
                            <br/><br/>
                            {echo $news->shortBody}
                        </p>
                        <hr/>
                    {/foreach}
                {/if}
                {else}
                    <p>Žádné novinky</p>
                {/else}
            </div><!--widgetcontent-->
        </div><!--widgetbox-->
    </div><!--one_half-->
    
    <div class="one_half last">
        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>Nejnovější galerie</span></h2></div>
            <div class="widgetcontent padding0 statement">
                <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
                    <colgroup>
                        <col class="con0" />
                        <col class="con1" />
                        <col class="con0" />
                    </colgroup>
                    <thead>
                        <tr>
                            <th class="head0">Název</th>
                            <th class="head1">Vytvořeno</th>
                            <th class="head0">Veřejná/Soukromá</th>
                        </tr>
                    </thead>
                    <tbody>
                        {if !empty($latestgallery)}
                            {foreach $gallery in $latestgallery}
                                <tr>
                                    <td>{echo $gallery->getTitle()}</td>
                                    <td>{echo $gallery->getCreated()}</td>
                                    <td>
                                        {if $gallery->isPublic}
                                            Veřejná
                                        {/if}{else}
                                            Soukromá
                                        {/else}
                                    </td>
                                </tr>
                            {/foreach}
                        {/if} 
                    </tbody>
                </table>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->
    </div><!--one_half-->

    <br class="clear-all"/><br />

    <div class="one_half ">
        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>Nejnovější členové</span></h2></div>
            <div class="widgetcontent padding0 statement">
                <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
                    <colgroup>
                        <col class="con0" /><col class="con1" />
                        <col class="con0" /><col class="con1" />
                    </colgroup>
                    <thead>
                        <tr>
                            <th class="head0">Foto</th>
                            <th class="head1">Jméno</th>
                            <th class="head0">Příjmení</th>
                            <th class="head1">Přidán</th>
                        </tr>
                    </thead>
                    <tbody>
                        {if !empty($latestmembers)}
                            {foreach $member in $latestmembers}
                                <tr>
                                    <td><img src="{echo $member->getImgThumb()}" alt="" height="80px"/></td>
                                    <td>{echo $member->getFirstname()}</td>
                                    <td>{echo $member->getLastname()}</td>
                                    <td>{echo $member->getCreated()}</td>
                                </tr>
                            {/foreach}
                        {/if} 
                    </tbody>
                </table>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->
    </div><!--one_half-->
    
    <div class="one_half last">
        <div class="widgetbox">
            <div class="title"><h2 class="general"><span>Nejnovější psi</span></h2></div>
            <div class="widgetcontent padding0 statement">
                <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
                    <colgroup>
                        <col class="con0" /><col class="con1" />
                        <col class="con0" /><col class="con1" />
                        <col class="con0" />
                    </colgroup>
                    <thead>
                        <tr>
                            <th class="head0">Foto</th>
                            <th class="head1">Jméno</th>
                            <th class="head0">Rasa</th>
                            <th class="head1">Majitel</th>
                            <th class="head0">Přidáno</th>
                        </tr>
                    </thead>
                    <tbody>
                        {if !empty($latestdogs)}
                            {foreach $dog in $latestdogs}
                                <tr>
                                    <td><img src="{echo $dog->getImgThumb()}" alt="" height="80px"/></td>
                                    <td>{echo $dog->getDogName()}</td>
                                    <td>{echo $dog->getRace()}</td>
                                    <td>{echo $dog->firstname." ".$dog->lastname}</td>
                                    <td>{echo $dog->getCreated()}</td>
                                </tr>
                            {/foreach}
                        {/if} 
                    </tbody>
                </table>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->
    </div><!--one_half-->
    
    
    <br class="clear-all"/><br />

</div><!--content-->