{if !empty($newsbatch)}
    {foreach $new in $newsbatch}
        <div class="news">
            <a href="/aktuality/r/{echo $new->urlKey}"><span class="newsTitle">{echo $new->title}</span></a><br/>
            <span class="newsCreated">{echo $new->created}</span><br/>
            <p class="newsBody">{echo $new->shortBody}</p>
        </div>
    {/foreach}
{/if}{else}
    <div>
        Nejsou žádné aktuality
    </div>
{/else}
