{if !empty($members)}
    {script $i=0}
    {foreach $user in $members}
        {script $i++}
        {script $dog = $user->getActiveDog()}
        <div class="dogUser">
            <div class="dogImg">
                <a data-lightbox="imageGr{echo $i}" 
                   data-title="{echo $user->firstname.' '.$user->lastname}" 
                   href="{echo $user->getImgMain()}">
                    <img src="{echo $user->getImgThumb()}"/>
                </a>
            </div>
            <div class="dogInfo">
                <span>Jméno:{echo $user->firstname.' '.$user->lastname}</span><br/>
                {if $dog !== null}
                <span>Pes: {echo $dog->getDogName()}</span><br/>
                <span>Rasa: {echo $dog->getRace()}</span><br/>
                {script $exams = $dog->getExams()}
                <span>Zkoušky:
                    {if !empty($exams)}
                        {foreach $exam in $exams}
                            {echo $exam->getShortcut()}
                        {/foreach}
                    {/if}{else}
                        Bez zkoušek
                    {/else}
                </span>
                {/if}
            </div>
            <div class="dogLogo">
                <img src="/public/images/user_logo.jpg"/>
            </div>
        </div>
    {/foreach}
{/if}{else}
    <div class="errorDiv">
        <span>Žádní členové</span>
    </div>
{/else}
