<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Content-Language" content="cs" />
        <meta http-equiv="CACHE-CONTROL" content="public">
        <meta name="viewport" content="width=device-width, maximum-scale=2.0, minimum-scale=1.0, initial-scale=1.0" />
        <meta name="keywords" content="" />
        <meta name="description" content="" />
        <meta name="author" content="Tomas Hodan" />
        <meta name="robots" content="INDEX,NOFOLLOW" />

        <link href="/public/css/custom/reset.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/public/css/plugins/smoothness/jquery-ui-1.10.4.custom.min.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/public/css/custom/styles.css" media="screen" rel="stylesheet" type="text/css" />
        <!--[if IE]> <link href="/public/css/styles.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->

        <!--[if lt IE 9]><script type="text/javascript" src="/public/js/plugins/html5.js"></script><![endif]-->
        <script type="text/javascript" src="/public/js/plugins/jquery-1.11.1.min.js"></script>
        <script type="text/javascript" src="/public/js/plugins/jquery-ui-1.10.4.custom.min.js"></script>

        <title></title>
    </head>
    <body lang="cs">
        <header>
            <div class="logo">
                <img src="../../../../public/images/logo.jpg"/>
            </div>
            <div class="nazev">
                <h1>ZKO Kostelec nad Labem č.796</h1>
            </div>
        </header>
        <div class="conteiner">
            <section class="navigation">
                <nav>
                    <ul>
                       <li><a href="/clenove">Členové</a></li> 
                       <li><a href="/galerie">Galerie</a></li> 
                       <li><a href="/aktuality">Aktuality</a></li> 
                       <li><a href="/historie">Historie</a></li> 
                    </ul>
                </nav>
            </section>
            <section class="content">
                {yield action}
            </section>
        </div>

        <footer>
            <section class="odkazy">
                <h1 class="footerH">Odkazy</h1>
                <a href="#">Chovná stanice ELZET</a><br/>
                <a href="#">Český kynologický svaz</a><br/>
                <a href="#">Zkušební řády</a>
            </section>
            <section class="kontakt">
                <h1 class="footerH">Kontakt</h1>
                <span>Tel: 777 222 444</span><br/>
                <span>E-mail: lz@seznam.cz</span><br/>
                <span>Najdete nás zde: <a href="#">mapa</a></span>
            </section>
            <section class="vytvoril">
                <h1 class="footerH">Vytvořil</h1>
                <span>Lukáš a Tomáš Hodáň</span><br/><span> Tomáš Sláma</span>
            </section>
        </footer>
        <!-- JS scripts --> 

        <!-- End JS scripts -->
</body>
</html>